[package]
name = "importer-backend"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
fancy-regex.workspace = true
glob.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio.workspace = true